
ITERATION_NUMBER = 2000
INITIAL_MAX_TABU_SIZE = 20
INC_TABU_SIZE_ITER = 5
SCHEDULE_PATH = "schedules/schedule_2016_september.json"

FULL_NBHD_ITERS = 16
EXTENDED_NBHD_ITERS = 8
WRKS_RANDOM_FACTOR = 0.25
